apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
                  limits:
                    cpu: "500m"
                    memory: "1Gi"

#This is an example of an nginx deployment configuration file. 
#It deploys 3 replicas of an nginx container. The container runs the latest nginx image and exposes port 80.